import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  // Users collection - stores additional user info beyond Clerk
  users: defineTable({
    userId: v.string(), // Clerk user ID
    name: v.optional(v.string()),
    createdAt: v.number(),
  })
    .index("by_userId", ["userId"])
    .index("by_createdAt", ["createdAt"]),

  // Skills collection - defines different skills users can practice
  skills: defineTable({
    name: v.string(), // e.g., "Basketball", "Piano", "LeetCode"
    categories: v.array(v.string()), // e.g., ["shooting", "dribbling"] for basketball
    createdBy: v.optional(v.string()), // userId who created this skill
    public: v.boolean(), // whether others can use this skill
    createdAt: v.number(),
  })
    .index("by_name", ["name"])
    .index("by_createdBy", ["createdBy"])
    .index("by_public", ["public"])
    .index("by_createdAt", ["createdAt"]),

  // Drills collection - individual practice exercises
  drills: defineTable({
    skillId: v.id("skills"), // reference to a Skill
    category: v.string(), // e.g., "dribbling"
    difficulty: v.union(
      v.literal("Beginner"),
      v.literal("Intermediate"),
      v.literal("Advanced")
    ),
    description: v.string(), // the actual drill generated by AI
    createdAt: v.number(),
    createdBy: v.string(), // userId
  })
    .index("by_skillId", ["skillId"])
    .index("by_category", ["category"])
    .index("by_difficulty", ["difficulty"])
    .index("by_skillId_and_category", ["skillId", "category"])
    .index("by_skillId_and_difficulty", ["skillId", "difficulty"])
    .index("by_createdBy", ["createdBy"])
    .index("by_createdAt", ["createdAt"]),

  // DrillSessions collection - tracks when users complete drills
  drillSessions: defineTable({
    userId: v.string(), // who did the drill
    drillId: v.id("drills"), // reference to a Drill
    completedAt: v.number(),
    notes: v.optional(v.string()), // optional user feedback or thoughts
  })
    .index("by_userId", ["userId"])
    .index("by_drillId", ["drillId"])
    .index("by_userId_and_completedAt", ["userId", "completedAt"])
    .index("by_completedAt", ["completedAt"]),
});
